### ISSUE TITLE
Spleef in game countdown;

### ISSUE THREAD

**Issue by aaomidi** [Kaos1337/SimpleSpleef-Evolution#1]
Well the problem is that sometimes , i still haven't found the reason) the in game countdown never starts and if we kill ourselves in the spleef arena the game never ends and the game stops working till i disable/enable it or restart the server.
I am using the spade method of the spleef arena, and the reason might be when someone doesn't do /spl ready??
Still not sure

**Comment by Kaos1337** [comment]
(The game never end because it isn't never started)
Can you post your config file? www.pastebin.com

**Comment by aaomidi** [comment]
http://pastebin.com/jvmCrsKB
Thanks :P

**Comment by Kaos1337** [comment]
This was the error: http://pastebin.com/LYcmnbmX
The issue is fixed with the version 3.4 (soon released).

**Comment by aaomidi** [comment]
Oh nice thanks man ;)
