### ISSUE TITLE
The start up block does not work

### ISSUE THREAD

**Issue by Kaos1337** [Kaos1337/SimpleSpleef-Evolution#13]
@Cronos79 reported:

The start up block does not work.

**Comment by Kaos1337** [comment]
can you post your config file?

**Comment by Cronos79** [comment]
http://pastebin.com/h0nyqQbE

**Comment by aaomidi** [comment]
Line 51 has to be true.

**Comment by Kaos1337** [comment]
I quote @aaomidi.
