### ISSUE TITLE
Consider name change or tutorials of different game types

### ISSUE THREAD

**Issue by FuzzyStatic** [Kaos1337/SimpleSpleef-Evolution#16]
I currently use this plug-in not only for Spleef, but for automated Arena battles and a Maze Race. I feel you guys should generalize the use of this plug-in more as it can serve multiple purposes. If you consider this and are curious of the game types I've created  using this plug-in you can check them out on mc.fuzzycraft.com:27861.

I apologize if this is redundant I have not spent the time to go through all current tickets.

**Comment by minecrafter** [comment]
Will likely not be done.

I'd rather not have to rename the project "GamingFramework".
