### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by RofelG** [Kaos1337/SimpleSpleef-Evolution#2]
The server wont run simplespleef. http://pastebin.com/Uc63T8Jr
Im running a 1.3.1 server with bukkit 1.3.2:R2.0 installed

**Comment by aaomidi** [comment]
Oh I know your problem SimpleSpleef has been written with Java 7, your server is Java 6 I suppose, Ask your server administrators to update their Java.

**Comment by RofelG** [comment]
Thank you i'll let you know how it turns out. That was fast though

**Comment by aaomidi** [comment]
Well Im not a developer of this plugin (trying to get there) :P I just answered with my experience I may be wrong.

**Comment by RofelG** [comment]
With your experience do you know how to write a batch file that uses java7 instead of 6? Can you help me?

**Comment by aaomidi** [comment]
Sure can i see your batch file?
use pastebin.com

**Comment by RofelG** [comment]
@ECHO OFF
SET BINDIR=%~dp0
CD /D "%BINDIR%"
"C:\Program Files (x86)\Java\jre7\bin\java.exe" -Xmx3072M -Xms3072M -jar craftbukkit-1.3.1-R2.0.jar
PAUSE

**Comment by aaomidi** [comment]
Can you tell me if you have this directory?:
C:\Program Files\Java\jre7\bin\

**Comment by RofelG** [comment]
no i dont

**Comment by aaomidi** [comment]
Ok I would suggest installing a 64bit Java http://download.oracle.com/otn-pub/java/jdk/7u6-b24/jre-7u6-windows-x64.exe

**Comment by RofelG** [comment]
So i just replace the java.exe location with C:\Program Files\Java\jre7\bin\java.exe?

**Comment by aaomidi** [comment]
Yep

**Comment by RofelG** [comment]
Wow amazing it works! Thank you

**Comment by aaomidi** [comment]
No probs ;)

**Comment by RofelG** [comment]
(0.0)b

**Comment by Kaos1337** [comment]
I confirm that we compile with java 7

**Comment by zorlax** [comment]
Thanks @aaomidi for the support.

**Comment by aaomidi** [comment]
:P
