### ISSUE TITLE
Could not pass EntityChangeBlockEvent to SimpleSpleef v3.4

### ISSUE THREAD

**Issue by MrPlantPlant** [Kaos1337/SimpleSpleef-Evolution#26]
The Console shows the error as this: 

8:07:12 PM GMT+01:00 CONSOLE: [SEVERE] Could not pass event EntityChangeBlockEvent to SimpleSpleef v3.4
8:07:12 PM GMT+01:00 CONSOLE: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityChangeBlockEvent.getEntity()Lorg/bukkit/entity/LivingEntity;

I have it running with Bukkit version 1.4.6 R0.1 Beta Build #2561.

I have it running with quite some other plugins running. HawkEye and Worldguard have had the same problem, but updating them solved the issue. The error shows up every half of a second or less, lagging the server quite a bit.

As we are still testing the plugin, 6 out of 7 permission groups dont have permission to use it. Could this be a problem? Oh, and i am running it with McMyAdmin, if this might be a problem, i don't know. If there is any other information you might need in order to get a view on things, and of course if you can be bothered about it, please mail me at adrian@freecraftserver.com. Thank you in advance.

**Comment by minecrafter** [comment]
Please use version 3.4.2. It has the op/default permissions and EntityChangeBlockEvent change.

**Comment by MrPlantPlant** [comment]
I think i am using it, but ill have a look downloading the latest one.

Thanks again.

EDIT: Yes, sorry, i cocked up, using the 1.3.2 version. Sorry for wasting your time.
