### ISSUE TITLE
HELP ME PLEASE!

### ISSUE THREAD

**Issue by Glasses4Geeks** [Kaos1337/SimpleSpleef-Evolution#27]
I run the /spla arena command and nothing works, could you please help me, I really want to use this plugin.

Info:

Minecraft Version:
1.4.6

Config for SimpleSpleef Evolution:
Left it at default.

Plugins:
- Essentials
- Anti-Cheat
- DwDNPC
- dynmap
- Lift
- EssentialsChat
- EssentialsProtect
- EssentialsSpawn
- World Edit
- PluginMetric
- SimpleSpleef Evolution

**Comment by minecrafter** [comment]
You must have not set things up properly.

Re-read the BukkitDev documentation.
