### ISSUE TITLE
Didnt find permissions

### ISSUE THREAD

**Issue by thegib3** [Kaos1337/SimpleSpleef-Evolution#29]
14:43:17 [INFO] [SimpleSpleef] Found WorldEdit 8-766eec6. Using it for selections. 14:43:17 [INFO] [SimpleSpleef] Metrics connection started. 14:43:17 [INFO] [SimpleSpleef] Permission plugin not found... shutting down! 14:43:17 [INFO] [SimpleSpleef] Disabling SimpleSpleef v3.4.2 14:43:17 [INFO] SimpleSpleef v3.4.2 is shutting down. 

Im using group manager

**Comment by minecrafter** [comment]
Make sure to use Vault.
