### ISSUE TITLE
Spleef and /fly from essentials.

### ISSUE THREAD

**Issue by aaomidi** [Kaos1337/SimpleSpleef-Evolution#3]
Well I was looking at the coding and saw that spleef doesn't set a player flying to false.
I tested this and I saw it is true, If I activate /fly while in survival mode and enter spleef I am still able to fly after the game starts.
Thanks for all the support.

**Comment by Kaos1337** [comment]
Try this dev version if fix it: http://www.mediafire.com/?rsiom861dmo6k98

**Comment by minecrafter** [comment]
Fixed
