### ISSUE TITLE
No permissions [bug] [high priority]

### ISSUE THREAD

**Issue by houtzager** [Kaos1337/SimpleSpleef-Evolution#34]
hello,
installed simplespleef-evolution for 1.4.6, i installed vault and worldedit and pex. i gave me all permissions for simplespleef and other plugins(-    '*'). there is no yaml error. but if i type /spl it say: 
/spl is the  SimpleSpleef command - You have no permissions to use it at all!
and if i do /spl join or /spla it will say:
you dont have permissions for the command join/admin. you need the permission simplespleef.join./simplespleef.admin. 
PLEASE HELP! 

thanks :P

**Comment by minecrafter** [comment]
Do not use PEX. It is fundamentally broken.

**Comment by houtzager** [comment]
whats wrong on pex? and what plugin do i have to use? and on another server it worked fine with PEX.

**Comment by minecrafter** [comment]
I use GroupManager and things work just fine.

**Comment by houtzager** [comment]
ye but whats wrong on pex? and on another server it worked fine with PEX.

**Comment by minecrafter** [comment]
https://docs.google.com/document/d/1BIgAU7senSG1hY0BjQAQFAnbuOqFhpln7ffN6pkOp4s/edit
