### ISSUE TITLE
floor doesn't get restored 

### ISSUE THREAD

**Issue by Jetjellybean** [Kaos1337/SimpleSpleef-Evolution#9]
After playing the Snow Block Floor doesn't get restored. 

I am using SimpleSpleef v3.4 for CB 1.3.1-R2.0 Aug 24, 2012. With Craftbukkit #2352 Beta 1.3.2 R0.1 and  I do not have Spout.

Here is my config

version: 3
language: en
settings:
  updateNotificationOnStart: false
  updateNotificationOnLogin: false
  defaultArena: default
  enableSigns: true
  useSignPermissions: true
  signsFirstLine: '[Spleef]'
  signsOnlyRightClick: false
  announceGame: true
  announceJoin: true
  announceTeam: false
  announceReady: false
  announceStart: true
  announceStop: true
  announceDelete: true
  announceCountdown: false
  announceLose: true
  announceWin: true
  announcePrize: true
  announcementRadius: -1
  sendMessagesToConsole: true
  preventTeleportingDuringGames: true
  keepOriginalLocationsSeconds: 3600
  changeGameModeBackToCreative: false
  enableStatistics: true
  statisticsModule: file
  statisticsSettings: false
arenas:
  default:
    name: Spleef Arena
    type: standard
    enabled: true
    minimumPlayers: 2
    maximumPlayers: 0
    remainingPlayersWin: 1
    announceOnJoin: true
    spleeferStart: true
    teamCommand: true
    teamBlockMaterialBlue: WOOL:11
    teamBlockMaterialRed: WOOL:14
    teamJoiningAlsoReadies: true
    useReady: false
    readyAutoStart: true
    readyBlockMaterial: '42'
    readyTimeout: 0
    emptyInventoryToJoin: false
    emptyInventoryToSpectate: false
    clearInventory: false
    addToInventory: false
    addInventoryItems:
    - 1:BOW
    - 64:ARROW
    entryFee: 0.0
    entryFeeGoesToPlayer: none
    entryFeeAmountToPlayer: 0.0
    giveItemPrizes: true
    itemPrizes:
    - 1:373:8204
    - 1:373:8193
    - 1:373:8225
    - 1:373:8233
    - 1:373:16425
    - 1:322
    - 1:BED
    - 6:BOOK
    - 1:CAKE
    - 1:357
    - 1:DIAMOND
    - 1:FLINT_AND_STEEL
    - 1:GOLD_INGOT
    - 4:IRON_INGOT
    - 1:382
    - 1:GOLD_HELMET
    - 1:381
    - 1:368
    - 1:350
    - 1:365
    prizeMoneyPerPlayer: 0.0
    prizeMoneyFixed: 0.0
    prizeExperiencePerPlayer: 10.0
    prizeExperienceFixed: 10.0
    refundMoney: 0.0
    loseOnTouchBlocks: true
    loseBlocks:
    - STATIONARY_WATER
    - STATIONARY_LAVA
    winOnTouchBlocks: false
    winBlocks:
    - GOLD_BLOCK
    loseOnDeath: true
    loseOnLogout: false
    noHunger: true
    noPvP: true
    blockDegeneration: -1
    degeneratingBlocks:
    - DIRT
    - GRASS
    - WOOL
    - SNOW_BLOCK
    - ICE
    - GLASS
    allowDigBlocks:
    - DIRT
    - GRASS
    - WOOL
    - SNOW_BLOCK
    - ICE
    - GLASS
    disallowDigBlocks:
    - STONE
    instantDig: true
    playersReceiveShovelAtGameStart: true
    playersLoseShovelAtGameEnd: true
    shovelItem: DIAMOND_SPADE
    countdownFrom: 3
    allowBlockPlacing: false
    blockDropping: true
    diggingIfArenaUndefined: floorOnly
    diggingIfFloorUndefined: inArena
    protectArena: true
    disallowCreatureSpawns: true
    enableExplosionsDuringGame: false
    restoreArenaAfterGame: true
    simpleRestorerBlock: GRASS
    restoreArenaAfterGameTimer: 0
    enableBackCommand: true
    arenaFloorDissolvesAfter: -1
    arenaFloorDissolveTick: 5
    arenaFloorRepairsAfter: -1
    arenaFloorRepairTick: 10
    arenaTimeout: 0
    arena:
      enabled: true
      a:
        world: Game1
        x: -190
        y: 63
        z: 231
      b:
        world: Game1
        x: -167
        y: 80
        z: 266
    floor:
      enabled: true
      a:
        world: Game1
        x: -187
        y: 72
        z: 237
      b:
        world: Game1
        x: -169
        y: 72
        z: 259
    lose:
      enabled: true
      a:
        world: Game1
        x: -189
        y: 67
        z: 235
      b:
        world: Game1
        x: -167
        y: 67
        z: 261
    win:
      enabled: false
      a:
        world: world
        x: 0
        y: 0
        z: 0
      b:
        world: world
        x: 0
        y: 0
        z: 0
    loungeSpawn:
      enabled: true
      world: Game1
      pitch: 10.499915
      yaw: -0.75042546
      x: -177.80694470443345
      y: 77.0
      z: 232.65328778869468
    gameSpawn:
      enabled: true
      world: Game1
      pitch: 9.29992
      yaw: 181.34958
      x: -178.168337991835
      y: 73.0
      z: 249.1567206609356
    redSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    blueSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    spectatorSpawn:
      enabled: true
      world: Game1
      pitch: 9.749919
      yaw: 182.24951
      x: -177.2084044686234
      y: 77.0
      z: 264.3173715797391
    loseSpawn:
      enabled: true
      world: Game1
      pitch: 9.749919
      yaw: 182.24951
      x: -177.2084044686234
      y: 77.0
      z: 264.3173715797391
    winnerSpawn:
      enabled: false
      world: world
      pitch: 0.0
      yaw: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
checkCommands:
  activateWhitelist: true
  whitelist:
- ^/spl
- ^/spla

**Comment by aaomidi** [comment]
The plugin currently has a few bugs which will get fixed soon ;)

**Comment by Kaos1337** [comment]
I'm not able to reproduce the issue, I tried with the grass, glass and snow block and all were restored, did you tried with other types?

**Comment by Jetjellybean** [comment]
I have not tried Grass and Glass.  I will try and let you know.  I also have multiverse plug in and this spleef arena is not at the mainworld.

**Comment by Kaos1337** [comment]
Ok,
I'll wait for a response with other materials.

**Comment by Jetjellybean** [comment]
Hello,   I just redid the snow block for the floor.  I destroyed all the old snow block and put the new snow block on.

Now it's working.  Thanks

**Comment by Kaos1337** [comment]
You are welcome, if you find other bugs feel free to open a new ticket.
